"""Add repo download status tracker

Revision ID: 1909e2f14477
Revises: ecf445b75259
Create Date: 2020-12-17 20:15:34.332811

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "1909e2f14477"
down_revision = "ecf445b75259"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "repo_downloadstatus",
        sa.Column("repo", sa.Text(), nullable=False),
        sa.Column("download_started", sa.DateTime(), nullable=True),
        sa.Column("download_finished", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("repo"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("repo_downloadstatus")
    # ### end Alembic commands ###
